#!/bin/sh

@ifdef "LAPTOP"
"""IN="eDP-1"
EXT1="DP-2-2"

DISPLAY_STATUS=$(xrandr)

if (echo $DISPLAY_STATUS | grep -E "$EXT1 disconnected.*"); then
    xrandr --output $IN --auto --output $EXT1 --off
else
    xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x120  --output $EXT1 --mode 1920x1200 --pos 1920x0
fi"""
"""# Sets the 1440p monitor as primary display, align bottom edges
xrandr --output DVI-I-2 --primary --output DVI-I-1 --pos 2560x390
# Load nvidia settings
nvidia-settings --load-config-only &"""
@endif

# Caps is control, left win is compose, ctrl-alt-bksp kills X
setxkbmap -option 'ctrl:nocaps,compose:lwin,terminate:ctrl_alt_bksp'
xrdb -merge .Xresources &
@ifdef "LAPTOP"
"""# Bind media keys
xbindkeys"""
@endif
# Hides cursor after 5 seconds
unclutter -idle 5 &
# Enable num lock
numlockx &
xmobar &
redshift &
exec ratpoison
