# Exports
export EDITOR=emacs
export BROWSER=chromium
export TERM=xterm
## Disable font anti-aliasing
export FT2_SUBPIXEL_HINTING=0
## GPG Agent
export GPG_TTY=$(tty)
@ifdef "LAPTOP" ""
"""## VSync Config
export __GL_SYNC_TO_VBLANK=1
export __GL_SYNC_DISPLAY_DEVICE=DVI-I-2
export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=DVI-I-2"""
@endif


# PATH
## pyenv
PATH=~/.pyenv/bin:$PATH
eval "$(pyenv init -)"
## poetry
PATH=~/.poetry/bin:$PATH
## nvm
source /usr/share/nvm/init-nvm.sh

# Credentials

source ~/.zcredentials
