# .zshrc - Z shell configuration
#
# By Antoine Busque <antoine@abusque.com>

# History settings
HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=5000
HISTORY_IGNORE="(ls*|ll*|true|cd*|git st|git pull|git lppg|git stash*|qng *)"
setopt HIST_IGNORE_ALL_DUPS
setopt APPEND_HISTORY

# Global options
setopt nomatch complete_aliases
unsetopt extendedglob notify

# Key bindings
## Emacs bindings
bindkey -e
## Delete key
bindkey    "^[[3~"          delete-char
bindkey    "^[3;5~"         delete-char

# Prompt
autoload -U promptinit
promptinit
prompt walters

# Completion
fpath=(~/.zsh/completion $fpath)
autoload -Uz compinit
compinit

zstyle ':completion:*' menu select=2
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*::::' completer _expand _complete _ignored _approximate
zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format $'\e[01;33m-- %d --\e[0m'
zstyle ':completion:*:messages' format $'\e[31m%d\e[0m'
zstyle ':completion:*' group-name ''
zstyle ':completion:*:manuals' separate-sections true
zstyle ':completion:*:processes' command 'ps -au$USER'
zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:kill:*' force-list always
zstyle ':completion:*:*:kill:*:processes' list-colors "=(#b) #([0-9]#)*=29=34"
zstyle ':completion:*:*:killall:*' menu yes select
zstyle ':completion:*:killall:*' force-list always
zstyle ':completion:*:(options|commands)' list-colors '=(#b)*(-- *)=0=36'
zstyle ':completion:*' ignored-patterns 'dockeb'

# Exports
export EDITOR=emacs
export BROWSER=chromium
export TERM=xterm
## Disable font anti-aliasing
export FT2_SUBPIXEL_HINTING=0
## GPG Agent
export GPG_TTY=$(tty)
@ifdef "LAPTOP" ""
"""## VSync Config
export __GL_SYNC_TO_VBLANK=1
export __GL_SYNC_DISPLAY_DEVICE=DVI-I-2
export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=DVI-I-2"""
@endif

# Aliases
## Utilities
alias rm='rm -I'
alias ls='ls --quoting=literal --color=auto --group-directories-first'
alias grep='grep --color=auto'
alias ll='ls -lh'
alias diff='colordiff -u'
alias ag='ag --hidden --path-to-ignore ~/.ignore'
## Color and paging
alias less='less -R'
alias grepc='grep --color=always'
alias agc='ag --color'
## Miscellaneous
alias bw='eboxbw PJ138'
alias ut='find . -name "*.[cChH]" | etags -'
alias docker='dockeb'
alias octave-gui='octave --force-gui'
@ifdef "LAPTOP" ""
"alias xsteam='startx /home/abusque/.steamxinitrc --'"
@endif


# PATH
## pyenv
PATH=~/.pyenv/bin:$PATH
eval "$(pyenv init -)"
